---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kb.kubekb.io
  resources:
  - knowledgebases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kb.kubekb.io
  resources:
  - knowledgebases/finalizers
  verbs:
  - update
- apiGroups:
  - kb.kubekb.io
  resources:
  - knowledgebases/status
  verbs:
  - get
  - patch
  - update
