apiVersion: kb.kubekb.io/v1alpha1
kind: KnowledgeBase
metadata:
  name: knowledgebase-sample
  namespace: default
spec:
  inferenceServer:
    provider: ollama
    model: llama3.2:3b
  vectorDB:
    provider: pgvector
    storage: 10Gi
  githubRepo: https://github.com/kubekb/kubekb
  githubBranch: main
